<?php

namespace WPSelenium\Utilities;

class CONSTS{

    CONST WPSELENIUM_TEMP_TEST_FILE = "WPSeleniumTest.temp.json";
    CONST WPSELENIUM_TEMP_TEST_DIR_KEY = "directories";
    CONST WPSELENIUM_TEMP_TEST_FILE_KEY = "files";

    CONST DOWNLOAD_FILE_DOWNLOADED = "DOWNLOAD_FILE_DOWNLOADED";
    CONST DOWNLOAD_FILE_FAILED = "DOWNLOAD_FILE_FAILED";
    CONST DOWNLOAD_FILE_ALREADY_EXISTS = "DOWNLOAD_FILE_ALREADY_EXISTS";

    CONST SUPPORTED_DRIVERS_CHROME = "chrome";
    CONST SUPPORTED_DRIVERS_FIREFOX = "firefox";

    CONST ANNOTATION_WP_BEFORE_RUN = "wpBeforeRun";

    CONST IS_PHPUNIT_SAMPLE_CONFIG = "wpselenium_sample_test";

    CONST PHPUNIT_CONFIG_TYPE_WPSELENIUM_CONFIG = "WPSELENIUM_CONFIG";
    CONST PHPUNIT_CONFIG_TYPE_PHPUNIT_CONFIG = "PHPUNIT_CONFIG";
    CONST PHPUNIT_CONFIG_TYPE_WPSELENIUM_SAMPLE = "WPSELENIUM_SAMPLE";
}